### ISSUE TITLE
Improve visual representation of landing page instructions

### ISSUE THREAD

**Issue by ZenoLC** [tuwien-csd/damap-frontend#110]
**Description**
The current instructions are a bit drab.
Improving the presentation of the steps could make it more inviting

**Proposed solution**
See attached image for inspiration.

**Comment by ZenoLC** [comment]
<img width="361" alt="image001" src="https://user-images.githubusercontent.com/7888518/231802262-476fd5e4-50bb-4fad-a498-0c0541c09938.png">

**Comment by ValentinFutterer** [comment]
Example from Laura https://github.com/tuwien-csd/damap-frontend/issues/167:

[LandingPageExample.zip](https://github.com/tuwien-csd/damap-frontend/files/14929066/LandingPageExample.zip)

![Image](https://github.com/tuwien-csd/damap-frontend/assets/80054001/771fe1ad-65b8-4a86-a341-976378068a6c)

**Comment by DerekMolnar** [comment]
Is this complete? @ValentinFutterer   If not, what is pending?
