### ISSUE TITLE
Add possibility to dismiss dropdown

### ISSUE THREAD

**Issue by DerekMolnar** [tuwien-csd/damap-frontend#158]
Dropdowns should have the possibility to be dismissed via a specific action button. Right now, clicking anywhere outside the field will dismiss it but it is not user friendly.

**Comment by DerekMolnar** [comment]
As discussed in December 19, 2023 Product Owner meeting

**Comment by DerekMolnar** [comment]
Need suggestions, then agreement on what it should look like. @lpandath are there angular components that you are aware of that you can suggest?

**Comment by DerekMolnar** [comment]
Adding examples of issue: 


![Image](https://github.com/tuwien-csd/damap-frontend/assets/150270835/e50f82fd-065e-4046-8347-5ac1696495ee)



![Image](https://github.com/tuwien-csd/damap-frontend/assets/150270835/00b8e5e6-43c3-4fc1-8cd2-6e804aeeb6e1)

**Comment by lpandath** [comment]
@DerekMolnar, maybe we can discuss this shortly first in the meeting today. Thank you!

**Comment by GeoffreyKarnbach** [comment]
https://stackoverflow.com/questions/58909906/close-dropdown-with-button-angular-material
