### ISSUE TITLE
Email disappears for contributor if they have ORCID ID

### ISSUE THREAD

**Issue by DerekMolnar** [tuwien-csd/damap-frontend#190]
**Describe the bug**
When adding a project contributor who has an ORCID ID and an email address, the email address disappears.  This happens both in DAMAP and the TU Wien DMP Tool

**Is this a regression?**
No.

**To Reproduce**

1. Go to 'People involved in data management'
2. Search for a person from the TU Wien address book that has an ORCID ID and email address, e.g. Tomasz or Christiane.   OR manually add a person with and email address and ORCID ID
3. Click "Save changes"
4. See email disapear

**Expected behavior**
All info input stays in tool, including email address

**Environment**
- Browser Edge version 122
- Damap and TU Wien DMP Tool

**Additional context**

**Comment by ValentinFutterer** [comment]
Bug is in backend, see https://github.com/tuwien-csd/damap-backend/issues/178
