### ISSUE TITLE
Estimated dataset size range disappears

### ISSUE THREAD

**Issue by DerekMolnar** [tuwien-csd/damap-frontend#202]
**Describe the bug**
In Step 3, when adding a dataset, one selects an estimated size from the dropdown list with 10 options that represent a size range, e.g. 100 to 500 GB.  However, once saved, the range changes in the table to the largest range listed.  This largest value also then shows in the template. 

**Is this a regression?**
No.

**To Reproduce**

1. Go to Step 3
2. Add a dataset under new datasets
3. Select an estimated size that is a range, e.g. 1-5 GB
4. See size in table change to <5 GB instead of 1-5 GB

**Expected behavior**
The size in table should change to 1-5 GB instead of <5 GB.  The change should also cascade to all the 3 templates. 

**Screenshots**

![Image](https://github.com/tuwien-csd/damap-frontend/assets/150270835/49498ab0-3a8e-4f6d-aab8-8b9d486a4506)

![Image](https://github.com/tuwien-csd/damap-frontend/assets/150270835/5dcfaa1a-4e06-4a68-9d16-8296dd09d5d3)

![Image](https://github.com/tuwien-csd/damap-frontend/assets/150270835/00dae277-dec0-4cce-9abf-a2e0ef4a4bc1)

**Comment by rekt-hard** [comment]
@lpandath can you also provide a PR for the back end to fix the export issue reported here?

**Comment by lpandath** [comment]
@rekt-hard yes, if there is no issue in place, ill create one and change that there and test it once more and link it here.

**Comment by rekt-hard** [comment]
Great thank you.
no need to create a separate issue (this one is already about the back end issue as well). Creating a PR and linking it will be enough
