### ISSUE TITLE
Dates saved are 1 Day behind dates selected at creation

### ISSUE THREAD

**Issue by ZenoLC** [tuwien-csd/damap-frontend#204]
**Describe the bug**
When creating a new DMP, the dates shown for created and modified (maybe others as well) are 1 Day behind the current date.
probably a timezone formatting issue.

**Is this a regression?**
Yes.
2.3.0 did not have this issue.
Possibly snuck in with quarkus upgrade and different date management.

**Steps to Reproduce**
1. Go to main page.
2. Click on 'Create new DMP'.
3. Save DMP.
4. See error in DMP list

**Expected behavior**
The dates should correspond to the actual dates.

**Environment**
 - firefox
 - Damap version 2.4.0-SNAPSHOT

**Comment by rekt-hard** [comment]
Issue has resurfaced.
Data sent from the front end subtracts one hour from the selected datetime. Might be due to the timezone

![image](https://github.com/tuwien-csd/damap-backend/assets/72449192/0513c361-b769-4661-bbdb-2802fb1a0579)
