### ISSUE TITLE
Global: Add new Damap Logo

### ISSUE THREAD

**Issue by ValentinFutterer** [tuwien-csd/damap-frontend#214]
**Changes**
Now that we have a logo and favicon, we should use it.
Replace the favicon with the damap favicon and the TU-Wien logo in the upper right with the damap logo. 
Both are accessible at https://colab.tuwien.ac.at/display/SRSI/DAMAP+logo
They also neeed to be colored in the Damap blue.

**Comment by lpandath** [comment]
@ValentinFutterer Do we want the yellow logo in the blue dmp tamplate here? have you discussed this with Derek? 



![Image](https://github.com/tuwien-csd/damap-frontend/assets/112856634/1f999e8d-3373-458e-bb56-f00f8cfc9dd2)

**Comment by ValentinFutterer** [comment]
> @ValentinFutterer Do we want the yellow logo in the blue dmp tamplate here? have you discussed this with Derek?
> 
> ![Image](https://private-user-images.githubusercontent.com/112856634/334104061-1f999e8d-3373-458e-bb56-f00f8cfc9dd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODgxMTMsIm5iZiI6MTcxNjg4NzgxMywicGF0aCI6Ii8xMTI4NTY2MzQvMzM0MTA0MDYxLTFmOTk5ZThkLTMzNzMtNDU4ZS1iYjU2LWYwMGY4Y2ZjOWRkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQwOTE2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTIyZWFlZWQ0NTJmZWMyM2Q4YmYyNmI2NDIxNDAxYjJhY2M4MmYzNGZhOGMzN2JlNzNmN2RkMjgzMDBmYWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iVEHhw-uS0H22L0oYH8z5kDooKDxgFrop6qix3BoRjk)

I have talked with Derek and we want it colored in the Damap blue - see the issue description.
