### ISSUE TITLE
In Step 7, closed data shoudn't allow a publication date

### ISSUE THREAD

**Issue by DerekMolnar** [tuwien-csd/damap-frontend#218]
**Describe the bug**
In step 7: Data access and licensing, if the Data Access is marked "Closed" there shouldn't be an Estimated publication date field

**Is this a regression?**
No.

**To Reproduce**

1. Go to Step 7
2. Click on Data Access
3. Select Closed
4. See Estimated publication date field

**Expected behavior**
The Estimated publication date field would be removed.  Alternatively be clearly greyed out

**Screenshots**

![Image](https://github.com/tuwien-csd/damap-frontend/assets/150270835/0b8dec43-1dd0-4e59-b95a-c3bd0ea5df3a)

**Comment by DerekMolnar** [comment]
@ChristianeStork please edit/clarify as needed

**Comment by ChristianeStork** [comment]
Perfect, thanks!
