### ISSUE TITLE
Upgrade angular version to v18

### ISSUE THREAD

**Issue by lpandath** [tuwien-csd/damap-frontend#226]
**Description**
[A clear and concise description of what you're missing.](https://angular.dev/update-guide?v=17.0-18.0&l=3)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

_If this issue requests multiple changes consider using checkboxes or lists._

**Comment by DerekMolnar** [comment]
Sorry, accidentally manually moved to Done, have moved back to In Progress
