### ISSUE TITLE
Add more info about person in search results

### ISSUE THREAD

**Issue by rekt-hard** [tuwien-csd/damap-frontend#255]
The name alone is often not enough to differentiate between people. Additional information like e-mail, ORCID should be shown in the result list.

**Comment by lpandath** [comment]
![Image](https://github.com/user-attachments/assets/a0e37588-de0a-4446-82a1-7f56cc4f6871)

@rekt-hard  Changes updated!

**Comment by DerekMolnar** [comment]
@lpandath looks good to me

**Comment by rekt-hard** [comment]
looking good. how about some spacing between elements and increasing the width of the result list? some addresses are cropped.
maybe also add the identifier type in front of the identifier, so we know which identifier it is
