### ISSUE TITLE
Action item not shown in dataset table

### ISSUE THREAD

**Issue by rekt-hard** [tuwien-csd/damap-frontend#262]
**Describe the bug**
In the dataset table, only the edit action item is shown. The delete action item is only shown as three dots (see bottom right corner of the image).

**Is this a regression?**
Yes/No.

**To Reproduce**

1. Create a DMP
2. Go to step 3
3. Add a dataset
4. Enter/Select:
  - Title: no action
  - Estimated type: Standard office documents
  - Estimated size: < 100 MB
5. See three dots instead of bin icon in table

**Expected behavior**
Available action icons should be shown

**Screenshots**
No bin icon
![Screenshot from 2024-07-16 10-37-39](https://github.com/user-attachments/assets/061b2742-7e45-41a0-9778-2e3adf182183)

Bin icon
![Screenshot from 2024-08-07 13-13-49](https://github.com/user-attachments/assets/acf46072-4f82-466d-86a7-364041b71b47)

**Environment**

- Browser: firefox
- Damap version: 4.0.0 +

**Additional context**

**Comment by GeoffreyKarnbach** [comment]
Can't reproduce the bug, the icon is displayed properly.

**Comment by rekt-hard** [comment]
Still occurs
![image](https://github.com/user-attachments/assets/3652f408-8c34-47f6-8c21-a626ba54f9ba)

**Comment by GeoffreyKarnbach** [comment]
What steps do you do to get to that point. If i just create one or several datasets manually, the bin icon is always visible.

**Comment by rekt-hard** [comment]
I have updated the steps to reproduce and an additional screenshot in the description above.

**Comment by GeoffreyKarnbach** [comment]
For the given steps to reproduce I have the icon displayed properly. If I understood correctly, the missing icon only occurs for some inputs?

![image](https://github.com/user-attachments/assets/22ad5255-c94a-4460-a967-65a768f0c25d)

**Comment by rekt-hard** [comment]
Yeah, looks like it. If the Datatype column spans two rows, the icon is displayed.
Just tested with Chrome without issues. Might be a Firefox specific issue.

**Comment by GeoffreyKarnbach** [comment]
Indeed for Firefox I can reproduce the issue. I somehow can't seem to find a fix for it, neither by changing some CSS experimentally in the browser inline, nor when assigning other material classes.
