### ISSUE TITLE
Change "enter a date range" to "enter start and end date"

### ISSUE THREAD

**Issue by DerekMolnar** [tuwien-csd/damap-frontend#265]
**Changes**
In the Choose Project section, change the "enter a date range" field to "enter start and end date" 

**Additional notes**
this is envisioned as a quick fix to make the field clearer to users

**Assumptions**
this is a quick fix

![Image](https://github.com/user-attachments/assets/0ad479e9-b935-4799-8537-67dba63bf672)

**Comment by GeoffreyKarnbach** [comment]
Already solved in:

https://github.com/tuwien-csd/damap-frontend/pull/281
