### ISSUE TITLE
Update Step 6 Legal aspects data owner question in DAMAP and export templates

### ISSUE THREAD

**Issue by DerekMolnar** [tuwien-csd/damap-frontend#268]
**Changes**
1) The last question in the Legal Aspects section is "who is the owner of the data and who controls access to tthe data?"  
**Fix:** change the wording to say "List who will have the rights to control access over which dataset(s)."

2) Currently the answer above does not appear in the templates 
**Fix:** add this statement “The following individual(s) hold rights and control access to the project data:”  and insert the answer from the above question to section 4b (Science Europe), 6.2 (Horizon Europe) and V.1 (FWF). 

3) Currently, if no answer to the question is provided, the phrase "There are no legal restrictions on the processing and disclosure of our data." appears
**Fix:** change the phrase to "“Information regarding rights and control of access to data has yet to be identified.”

4) Adjust the verbiage for "Intellectual property rights and ownership" sections in templates
**Fix:**  change the name of the section to "Intellectual property rights and rights of use" in 4b (Science Europe), 6.2 (Horizon Europe) and V.1 (FWF).

**Comment by DerekMolnar** [comment]
@ChristianeStork please confirm I've captured the changes from our discussion.

**Comment by ChristianeStork** [comment]
3.: Make the phrase a full sentence: "Information ... identified."

The rest is fine!
