### ISSUE TITLE
Step 10 Costs

### ISSUE THREAD

**Issue by lpandath** [tuwien-csd/damap-frontend#276]
**Description**
Modify the "add cost" dropdown menu to clarify the term "Personnel" by changing it to "Personnel (Data Steward)" or different naming. This will reduce misunderstandings regarding the costs being referred to.

**Describe the solution you'd like**

**Describe alternatives you've considered**
The "add cost" dropdown menu should display the term "Personnel (Data Steward)" or similar instead of just "Personnel".

**Additional context**

_If this issue requests multiple changes consider using checkboxes or lists._

**Comment by DerekMolnar** [comment]
@ChristianeStork what do you think about this proposed change?

**Comment by ChristianeStork** [comment]
I agree. The only issue could be the term "Data Steward" as not everybody is used to it/likes it. Please check with Tomasz.

**Comment by DerekMolnar** [comment]
@TomMiksa thoughts about this change to the cost step?

**Comment by TomMiksa** [comment]
I can live with it. It narrows down what kind of Personnel we mean.
