### ISSUE TITLE
Redirect user to edit url after creating a DMP and initially saving it

### ISSUE THREAD

**Issue by GeoffreyKarnbach** [tuwien-csd/damap-frontend#301]
**Description**
Right now, the user can create a DMP and keep editing it on the same URL (/dmp). If for some reason, one would like to check the progress and for instance refreshes the page, a new DMP is created and the next time it is saved, an additional "updated" DMP is created, with the initially created DMP not being updated.

**Describe the solution you'd like**
Redirect the user to (/dmp/{id}) once the DMP has been initially saved. Therefore, refreshing the page would still update the same DMP next time changes are submitted.

**Comment by rekt-hard** [comment]
Would changing the url after the first save/create also suffice?
Something like `document.location.href = ...;`

Probably less change and easier for the user as it will not refresh the whole site.
