### ISSUE TITLE
Sidenav: Username is hidden due to wrong color

### ISSUE THREAD

**Issue by ValentinFutterer** [tuwien-csd/damap-frontend#305]
**Describe the bug**
here should normally be a username - but it is not visible due to the wrong color being used.
<img width="268" alt="image" src="https://github.com/user-attachments/assets/3ac1efb6-240e-4c0f-a87f-796f8caeb1c1">

Also kinda related https://github.com/tuwien-csd/damap-backend/issues/253

**Is this a regression?**
Yes.

**Expected behavior**
The name should be visible.

**Environment**

- Browser [e.g. firefox, chrome]
- Damap version 4.0.0

**Comment by rekt-hard** [comment]
@lpandath Has this been fixed via the sidenav PR of yours already?

**Comment by lpandath** [comment]
@rekt-hard yes, now it looks like this:
![image](https://github.com/user-attachments/assets/d6aad751-482e-4321-88c7-d724d78fb30b)

**Comment by rekt-hard** [comment]
Closing this as the color is set based on a variable https://github.com/tuwien-csd/damap-frontend/blob/922ef3b8c98f9e9ed883407711ca4a9a0f737b4e/apps/damap-frontend/src/app/components/layout/layout.component.css#L260
