### ISSUE TITLE
Step 7: add data restriction answer under current table in templates

### ISSUE THREAD

**Issue by DerekMolnar** [tuwien-csd/damap-frontend#327]
**Describe the bug**
In Step 7, Data access and licensing, if a data set is restricted or closed, an explanation about why the data will not be accessible or is restricted is needed.  The answer to this question does not populate in any fields in the templates, even though there is a field for it in a table.  To avoid overcrowding of the table, the Restrictions/embargo reasons should be put under the table in a new section on each of the templates.  This will also mean removing the restrictions/embargo reasons from the table.

**Is this a regression?**
No

**To Reproduce**

1. Go to 'Step 7'
2. Select  'Closed' under Data Access selection for your dataset
3. Provide text explanation in the "Explain why..." field
4. See that your answer above did not populate the table. 

**Screenshots**
![Image](https://github.com/user-attachments/assets/d15ecb4f-850c-4081-af68-aaa5682266ac)

**Comment by ValentinFutterer** [comment]
Already fixed by backend-PR https://github.com/tuwien-csd/damap-backend/pull/265
