### ISSUE TITLE
UI: Remove "ChangeDetectionStrategy.OnPush" from Layout Component

### ISSUE THREAD

**Issue by GeoffreyKarnbach** [tuwien-csd/damap-frontend#389]
**Describe the bug**
Remove the "ChangeDetectionStrategy.OnPush" from the Layout Component TS File (Line 29). It has been previously removed but returned in the new UI commit, leading to the Storage Table in the Admin UI to only load once the header of the table is hovered.

Verify, that the detection for "isCollapsed" still works without the OnPush Strategy.

**Is this a regression?**
Yes

**Comment by lpandath** [comment]
@GeoffreyKarnbach ChangeDetectionStrategy.OnPush was used to improve performance, but it’s not needed. 
https://blog.angular-university.io/onpush-change-detection-how-it-works/

Everything, like isCollapsed, works fine with the default change detection.
