### ISSUE TITLE
Step 7 visual changes

### ISSUE THREAD

**Issue by ZenoLC** [tuwien-csd/damap-frontend#47]
- Improve visibility of questions at the bottom.
- Move "Data Access" dropdown to be vertically below publication date (sometimes not perceived because it is placed in the corner).
- Set "Date of deletion" per default to the project end date.
- Change license selector button to be a text button labeled "License selector" (colored button) 
- Add information when hovering license selector button: "Choose a license from the list or use the license selector to find an appropriate license." 
- set license to "CC-BY" as default value
- delete first half of sentence ("For following [...] open access,")

**Comment by lpandath** [comment]
@clarascu this PR is updated!
