### ISSUE TITLE
Step 8 changes

### ISSUE THREAD

**Issue by ZenoLC** [tuwien-csd/damap-frontend#48]
- move "Set retention period for datasets" component in between list of selected repositories and list of selectable repos.
- set retention period to 10 years by default
- filter list of available datasets here to the list of actually assigned datasets (assigned to repos)
- Add text to retention period collapsible component (ask RDM for text resource).

**Comment by DerekMolnar** [comment]
Verbiage for retention period will be placed in this issue: 
https://github.com/tuwien-csd/damap-frontend/issues/169
